services:
  - type: web
    name: wedding-planner
    env: docker
    plan: free
    repo: https://github.com/manikantaweddingplanner/weddingplanner
    dockerfilePath: Dockerfile
    branch: master
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_USERNAME
        value: YOUR_DB_USER
      - key: DB_PASSWORD
        value: YOUR_DB_PASS
